# src/Champloo/TaxonomieBundle/Resources/config/routing.yml

champloo_taxonomie_index:
    path:     /admin/taxonomie
    defaults: { _controller: ChamplooTaxonomieBundle:Taxonomie:indexTaxonomie }

champloo_taxonomie_vocabulaire_ajouter:
    path:     /admin/taxonomie_ajouter_vocabulaire
    defaults: { _controller: ChamplooTaxonomieBundle:Taxonomie:ajouterVocabulaire }

champloo_taxonomie_terme_ajouter:
    path:     /admin/taxonomie_ajouter_terme/{terme_slug}
    defaults: { _controller: ChamplooTaxonomieBundle:Taxonomie:ajouterTerme }

champloo_taxonomie_editer:
    path:     /admin/taxonomie_editer/{terme_slug}
    defaults: { _controller: ChamplooTaxonomieBundle:Taxonomie:editerTerme }

champloo_taxonomie_supprimer:
    path:     /admin/taxonomie_supprimer/{terme_slug}
    defaults: { _controller: ChamplooTaxonomieBundle:Taxonomie:supprimerTerme }

champloo_taxonomie_test:
    path:     /admin/taxonomie_test
    defaults: { _controller: ChamplooTaxonomieBundle:Smartlink:smartlink }