# router pour les pages de groupe utilisateur
fos_user_group_list:
    path: /groupe_liste
    defaults: { _controller: FOSUserBundle:Group:list }
    methods: [GET]

fos_user_group_new:
    path: /groupe_nouveau
    defaults: { _controller: FOSUserBundle:Group:new }
    methods: [GET, POST]

fos_user_group_show:
    path: /{groupeName}
    defaults: { _controller: FOSUserBundle:Group:show }
    methods: [GET]

fos_user_group_edit:
    path: /{groupeName}/edition
    defaults: { _controller: FOSUserBundle:Group:edit }
    methods: [GET, POST]

fos_user_group_delete:
    path: /{groupeName}/suppression
    defaults: { _controller: FOSUserBundle:Group:delete }
    methods: [GET]