# router pour la page profil des utilisateurs
champloo_userbundle_profil:
    resource: "@ChamplooUserBundle/Resources/config/routing/profil.yml"

# router pour les pages inscription des utilisateurs
champloo_userbundle_inscription:
    resource: "@ChamplooUserBundle/Resources/config/routing/inscription.yml"

# router pour les pages connexion & deconnexion des utilisateurs
champloo_userbundle_securite:
    resource: "@ChamplooUserBundle/Resources/config/routing/securite.yml"

# router pour les pages de réinitialisation du mot de passe utilisateur
champloo_userbundle_resetting:
    resource: "@ChamplooUserBundle/Resources/config/routing/resetting.yml"

# router pour les pages de groupe utilisateur
# champloo_userbundle_groupe:
#     resource: "@ChamplooUserBundle/Resources/config/routing/groupe.yml"