<?php

namespace Champloo\CommentaireBundle\Entity;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Fonction de recherce pour afficher tout les commentaire d'un article ($id)
     */
	public function findByArticleListeCommentaire($articleId)
	{
	$qb = $this->createQueryBuilder('c')
			   ->leftJoin('c.user', 'u') // jointure avec les utilisateurs
			   		->addSelect('u') // sélection de l'alias 'u'
			   		->orderby('c.datecreation', 'DESC')
			   ->where('c.article = :id')
			   		->setParameter ('id', $articleId)
	;

	return $qb
		->getQuery()
		->getResult();
	}
}

