<?php

namespace Champloo\TaxonomieBundle\Entity;

/**
 * VocabulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
