<?php

namespace Champloo\TaxonomieBundle\Entity;

/**
 * SmartlinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartlinkRepository extends \Doctrine\ORM\EntityRepository
{

}
