<?php

namespace Champloo\TaxonomieBundle\Entity;

/**
 * TermeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermeRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindSmartLink()
	{
		$qb = $this->createQueryBuilder('t');
		$qb->select('t.title', 't.lien');
		$qb->where('t.lien is not null');
		
		return $qb			
			->getQuery()
			->getResult();
			

	}
}
