# src/Champloo/SiteBundle/Resources/config/routing.yml


# Route pour le controller Homepage

champloo_site_homepage:
    path:     /
    defaults: { _controller: ChamplooSiteBundle:Homepage:index }


# Route pour le controller Article

champloo_site_actu:
    path:     /actu/{page}
    defaults: { _controller: ChamplooSiteBundle:Article:index }
    requirements:
        page: \d+

champloo_site_article_lire:
    path:     /article/{article_slug}
    defaults: { _controller: ChamplooSiteBundle:Article:lire }
    methods: [GET]

champloo_site_article_ajouter:
    path:     /ajouter
    defaults: { _controller: ChamplooSiteBundle:Article:ajouter }

champloo_site_article_editer:
    path:     /editer/{article_slug}
    defaults: { _controller: ChamplooSiteBundle:Article:editer }

champloo_site_article_supprimer:
    path:     /supprimer/{article_slug}
    defaults: { _controller: ChamplooSiteBundle:Article:supprimer }


# Route pour le controller Categorie

champloo_site_categorie_index:
    path:     /admin/categorie
    defaults: { _controller: ChamplooSiteBundle:Categorie:indexCategorie }

champloo_site_categorie_ajouter:
    path:     /admin/ajouter_categorie
    defaults: { _controller: ChamplooSiteBundle:Categorie:ajouterCategorie }

champloo_site_categorie_editer:
    path:     /admin/editer_categorie/{categorie_slug}
    defaults: { _controller: ChamplooSiteBundle:Categorie:editerCategorie }

champloo_site_categorie_supprimer:
    path:     /admin/supprimer_categorie/{categorie_slug}
    defaults: { _controller: ChamplooSiteBundle:Categorie:supprimerCategorie }

champloo_site_sous_categorie_ajouter:
    path:     /admin/ajouter_sous_categorie
    defaults: { _controller: ChamplooSiteBundle:Categorie:ajouterSousCategorie }

champloo_site_sous_categorie_editer:
    path:     /admin/editer_sous_categorie/{sous_categorie_slug}
    defaults: { _controller: ChamplooSiteBundle:Categorie:editerSousCategorie }

champloo_site_sous_categorie_supprimer:
    path:     /admin/supprimer_sous_categorie/{sous_categorie_slug}
    defaults: { _controller: ChamplooSiteBundle:Categorie:supprimerSousCategorie }