<?php

namespace Champloo\SiteBundle\Entity;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticles($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('a')
			->orderBy('a.datecreation', 'DESC')
			->getQuery()
		;
		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

}
