<?php

namespace Champloo\SiteBundle\Entity;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Fonction de recherce pour afficher tout les sous-catégories d'une
	 * catégorie
     */
	public function myFindCategorie()
	{
	$qb = $this->createQueryBuilder('c')
			   ->leftjoin('c.sousCategories', 'souscat') // jointure avec les catégories
			   		->addSelect('souscat') // sélection de l'alias 'souscat' en plus de la sélection 'c'
			   // ->orderby('souscat.nom', 'ASC') //classement par ordre alphabétique en fonction du non de la sous-cat
			   // ->where('souscat.categorie = c.id') //où la sélection se fait en fonction de l'id
			   
	;

	return $qb
		->getQuery()
		->getResult();
	}
}
