# src/Champloo/CommentaireBundle/Resources/config/routing.yml

champloo_commentaire_ajouter:
    path:     /ajouter/{id}/commentaire
    defaults: { _controller: ChamplooCommentaireBundle:Commentaire:ajouterCommentaire }
    requirements:
        page: \d+

champloo_commentaire_editer:
    path:     /editer/commentaire/{id}
    defaults: { _controller: ChamplooCommentaireBundle:Commentaire:editerCommentaire }
    requirements:
        page: \d+

champloo_commentaire_supprimer:
    path:     /supprimer/commentaire/{id}
    defaults: { _controller: ChamplooCommentaireBundle:Commentaire:supprimerCommentaire }
    requirements:
        page: \d+