<?php

namespace Champloo\SiteBundle\Entity;

/**
 * sousCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousCategorieRepository extends \Doctrine\ORM\EntityRepository
{

}
